### Rest client VSextension test

################
###   CART   ###
################

### GET CART BY ID
GET http://localhost:8081/api/cart/1/products HTTP/1.1

### DELETE CART BY ID
DELETE http://localhost:8081/api/cart/1 HTTP/1.1

### POST ADD CART
POST http://localhost:8081/api/cart/ HTTP/1.1
Content-Type: application/json

{
    "products": []
}

### POST ADD PRODUCT TO CART
POST http://localhost:8081/api/cart/1/products HTTP/1.1
Content-Type: application/json

{
    "id_prod": 1
}

### DELETE PRODUCT ON CART BY ID
DELETE http://localhost:8081/api/cart/1/products/1 HTTP/1.1
