### Rest client VSextension test

####################
###   PRODUCTS   ###
####################

### GET ALL PRODUCTS
GET http://localhost:8081/api/products/ HTTP/1.1

### GET PRODUCT BY ID
GET http://localhost:8081/api/products/1 HTTP/1.1

### DELETE PRODUCT BY ID
DELETE http://localhost:8081/api/products/1 HTTP/1.1
Authorization: admin

### POST ADD PRODUCT
POST http://localhost:8081/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: admin

{
    "name": "Tolkien Deluxe Pack",
    "desc": "The Hobbit + Lord of the Ring Trilogy",
    "code": "77650217",
    "url": "https://images-na.ssl-images-amazon.com/images/I/A1EgynjIE-L.jpg",
    "price": "149.99",
    "stock": "980"
}

### PUT UPDATE PRODUCT
PUT http://localhost:8081/api/products/1 HTTP/1.1
Content-Type: application/json
Authorization: admin

{
    "name": "Tolkien Deluxe Edition",
    "stock": "984"
}
